jokes: list[str] = [
    "Por que a galinha atravessou a rua? Para chegar ao outro lado.",
    "Qual é o cúmulo da rapidez? Chutar uma perna de pau.",
    "O que o zero falou para o oito? Bonito cinto!",
    "Por que o jacaré tirou o jacarezinho da escola? Porque ele réptil de ano.",
    "Por que o galo foi ao médico? Porque ele estava com gripe aviária.",
    "O que o tomate foi fazer no banco? Tirar extrato ketchup.",
    "Por que a aranha é o animal mais carente do mundo? Porque ela é um aracneedyou.",
    "Qual é o doce preferido do átomo? Pé-de-moléculas.",
    "Qual é o lugar mais tranquilo do mundo? O dentista, porque ali ninguém abre a boca.",
    "Como o elétron atende ao telefone? Próton.",
    "O que o lápis disse para a borracha? Você é a minha melhor amiga!",
    "Por que a matemática não tem namorado? Porque ela tem muitos problemas.",
    "Por que a bola de chiclete nunca foi ao baile? Porque ela gruda em todo mundo.",
    "O que o pato falou para a pata? Vem quá!",
    "O que o zero disse para o oito? Uau, que cinto maneiro!",
    "Por que a minhoca não brinca no playground? Porque ela não tem braços.",
    "Qual é o contrário de volátil? Vem cá sobrinho.",
    "Por que a formiga tem quatro patas? Porque se tivesse cinco seria uma moto.",
    "Por que o livro de matemática cometeu suicídio? Porque tinha muitos problemas.",
    "Qual é o animal mais antigo do mundo? A zebra, porque está sempre em preto e branco."
]